### ISSUE TITLE
Compensaciones: Browser freezes when saving strategies

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero#117]
Browser freezes after confirming you want to save the strategies, even though it saves them to the database.

Browser: Firefox 63.0.1

![image](https://user-images.githubusercontent.com/5290060/49762067-b5314880-fc96-11e8-8525-ae3122ecc7bd.png)

**Comment by alegnaaived** [comment]
Fixed on #118 Hotfix-1.2.3
